### ISSUE TITLE
Unexpected MMA layout version found"' failed (gptq_for_llama)

### ISSUE THREAD

**Issue by alexandme** [paolorechia/learn-langchain#9] opened 2023-04-28 01:03 UTC
I'm getting into this issue when try to run this on Paperspace linux instance with nvidia quadro p5000
CUDA: Cuda compilation tools, release 10.1, V10.1.243

The same problem was reported here: https://github.com/oobabooga/text-generation-webui/discussions/1461

`root@np2hkqa6bg:/notebooks/learn-langchain# uvicorn servers.vicuna_server:app 
Using config:  {'base_model_size': '13b', 'use_4bit': True, 'use_fine_tuned_lora': False, 'lora_weights': None, 'device': 'cuda', 'model_path': None, 'checkpoint_path': None}
Loading model ...
Found 3 unique KN Linear values.
Warming up autotune cache ...
  0%|                                                                                                             | 0/12 [00:00<?, ?it/s]python3.9: /project/lib/Analysis/Utility.cpp:136: bool mlir::supportMMA(mlir::Value, int): Assertion `(version == 1 || version == 2) && "Unexpected MMA layout version found"' failed.`

**Comment by paolorechia** [comment] 2023-04-28 05:40
So if understood this correctly the gptq-for-llama version that I used does not work with your setup? 

A solution would be to fork gptq-for-llama repository and install it through pip, instead of using the copy-paste folder that I used.

We could also add tags to the fork, so you can easily modify the requirements to use the tag of a version that works for you.

**Comment by paolorechia** [comment] 2023-04-28 05:41
Although actually we would have to hotfix the working version, since I had to make the modules importable to use in my server.

Do you happen to know the commit that worked for you?

**Comment by paolorechia** [comment] 2023-04-28 13:26
@aalyushin did you try downgrading the Triton package you're using? I took a look at the issue you mentioned and it seems to mention a recent PR in `openai/triton` repository.

It could be that just downgrading the triton package is enough, but I'm not sure. Since I can't reproduce your problem, it's hard for me to fix it on my own.

**Comment by aalyushin** [comment] 2023-04-28 14:26
@paolorechia Thank you for looking into this. This evening I will check and report here

**Comment by alexandme** [comment] 2023-04-29 01:53
Tried 

```
pip3 uninstall triton
pip3 install triton==2.0.0
```
(that is a previous version according to https://pypi.org/project/triton/#history)

However, same result running
```
(learn-langchain) root@nruhunmi2b:/notebooks/learn-langchain# uvicorn servers.vicuna_server:app
Using config:  {'base_model_size': '7b', 'use_4bit': True, 'use_fine_tuned_lora': False, 'lora_weights': None, 'device': 'cuda', 'model_path': None, 'model_checkpoint': None}
Loading model vicuna-7B-1.1-GPTQ-4bit-128g  checkpoint vicuna-7B-1.1-GPTQ-4bit-128g/vicuna-7B-1.1-GPTQ-4bit-128g.safetensors
Loading model ...
```

In the end geting: 

```
Found` 3 unique KN Linear values.
Warming up autotune cache ...
  0%|                                                                                                        | 0/12 [00:00<?, ?it/s]python: /project/lib/Analysis/Utility.cpp:136: bool mlir::supportMMA(mlir::Value, int): Assertion `(version == 1 || version == 2) && "Unexpected MMA layout version found"' failed.
Aborted (core `dumped)
```

**Comment by paolorechia** [comment] 2023-04-29 06:09
Dang, sorry to hear. 

Our next option is creating a new fork of gptq-For-Llama based on the stable version. Any chances you’re able to create this fork and maintain it? If not I’ll eventually look into it, but might take some time.

It seems like another user is facing a similar problem:

https://github.com/paolorechia/learn-langchain/issues/10#issuecomment-1528180612

**Comment by alexandme** [comment] 2023-04-29 13:32
@paolorechia Found this link on reddit today: https://www.reddit.com/r/LocalLLaMA/comments/12smm1m/is_it_possible_to_run_gptq_quantized_4bit_13b/

Followed this instructions (on slightly different machine than I was using later) https://gitlab.tarsis.org/machine-learning/rpstable
And it seems to be working, later today I will share details

That repository also uses gptq-For-Llama, just for your reference.

In terms of your question above
_Any chances you’re able to create this fork and maintain it?_
I would love to try, however I do not have much dev background, hopefully gpt4 will help me on my mission )

**Comment by paolorechia** [comment] 2023-04-29 21:06
Attempted to address this issue here: https://github.com/paolorechia/learn-langchain/pull/12

Not yet working as expected.

**Comment by paolorechia** [comment] 2023-04-30 21:14
Hi, @alexandme, I added support to use text-generation-webui as the backend, does that work for you? Note: you might still not be able to use the quant version with it, since it turns out the `text-generation-webui` does not work with the newest quant versions either.

https://github.com/paolorechia/learn-langchain#option-1---text-generation-webui-new-on-30042023

**Comment by paolorechia** [comment] 2023-05-01 13:59
Hey, if you load a slightly older version as explained here: https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g#gibberish-output

It should work with the text-generation-webui backend. I'm closing this issue as it should be solved now by this new backend. Let me know if you still run into issues.

**Closed by paolorechia** 2023-05-01 13:59 UTC
Labels: bug, help wanted, good first issue

**Comment by alexandme** [comment] 2023-05-02 00:18
@paolorechia Thank you, works for me with text-generation-webui!
